# 在打包为jar后，可以直接将配置文件放置到jar包的同级目录或config文件夹下（优先读取config文件夹下，然后同级，最后jar包内)
server:
  port: 8089 # 运行的端口
  servlet:
    # 前端控制器的监听路径,yaml配置此路径会报错
    # path: *.action
    # 访问的前缀
    context-path: /plms

# 输出的日志级别
logging:
  level:
    org:
      springframework: info

# druid spring boot 配置
druidDataSource: &druidDataSource # 别名
  filters: stat
  maxActive: 50
  initialSize: 1
  maxWait: 60000
  minIdle: 10
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  maxOpenPreparedStatements: 100
  removeAbandoned: true
  removeAbandonedTimeout: 1800
  logAbandoned: true
  type: com.alibaba.druid.pool.DruidDataSource

spring:
  # rabbitmq 配置
  rabbitmq:
    host: 192.168.6.7
    port: 5672
    username: admin
    password: 123456

#spring:
#  datasource:
#    druid:
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/how2java?Unicode=true&characterEncoding=UTF-8
#      <<: *druidDataSource # *引用别名， << 表示合并到当前

# 多数据源配置
multiple:
  datasource:
    druid:
      master:
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/how2java?Unicode=true&characterEncoding=UTF-8
        <<: *druidDataSource # *引用别名， << 表示合并到当前
      slave:
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/wpc?Unicode=true&characterEncoding=UTF-8
        <<: *druidDataSource # *引用别名， << 表示合并到当前

  #redis配置
  redis:
    database: 0
    # Master的ip地址
    host: 188.131.147.87
    # 端口号
    port: 6379
    # 客户端超时时间
    timeout: 10s
    jedis:
      pool:
        # 连接池的最大数据库连接数
        max-active: 600
        # 最大空闲数
        max-idle: 300
        # 最大建立连接等待时间
        max-wait: 1s

#mybatis-plus配置
mybatis-plus:
  config-location: classpath:mybatis-config/mybatis-config.xml
  type-aliases-package: com.jikuodong.plms.po
  mapper-locations: classpath:mapper/*.xml
  check-config-location: false # 不检查Mybatis XML 的存在
  global-config:
    refresh: false # 自动刷新mapper，生产需要关闭，调试神器

# pageHelper分页配置
pagehelper:
  # 设置为true时，会将RowBounds第一个参数offset当成pageNum页码使用
  offset-as-page-num: true
  # 设置为true时，使用RowBounds分页会进行count查询
  row-bounds-with-count: true
  # 设置为true时，如果pageSize=0或者RowBounds.limit = 0就会查询出全部的结果
  page-size-zero: true
  # 分页参数合理化，默认false禁用，禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 为了支持startPage(Object params)方法，增加了一个`params`参数来配置参数映射，用于从Map或ServletRequest中取值
  params: pageNum=start;pageSize=limit;
  # 支持通过Mapper接口参数来传递分页参数
  support-methods-arguments: true
